---
- name: Download nebula binaries
  get_url:
    url: https://github.com/slackhq/nebula/releases/download/v1.0.0/nebula-linux-amd64.tar.gz
    dest: /tmp/nebula-linux-amd64.tar.gz

- name: Extract nebula binaries to the app directory
  unarchive:
    src: /tmp/nebula-linux-amd64.tar.gz
    dest: /var/lib/nebula

- name: Set Nebula config
  template:
    src: templates/config.yml.j2
    dest: /etc/nebula/config.yml
    owner: nebula
    group: nebula
    mode: '0644'

- name: Set Nebula service
  template:
    src: files/nebula.service
    dest: /etc/systemd/system/nebula.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - "Start Nebula node service"
